disabled_rules:
- force_try
- nesting
- identifier_name
- empty_enum_arguments
- vertical_parameter_alignment

line_length: 200

type_body_length:
- 300
- 400

file_length:
    warning: 500
    error: 1200
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

type_name:
    min_length: 4
    max_length:
    warning: 40
    error: 50

excluded:
- Pods

reporter: "xcode"
